### ISSUE TITLE
Rework channel membership functionality

### ISSUE THREAD

**Issue by MykeMyke** [OperationXen/UnseenServant#319]
When players are added, removed or drop from game channels there is a regular (but inconsistent) tendency for the channel membership to de-sync. This often results in newly added players not being able to see the channel, resulting in user frustration. The existing `/reset_channel_membership` command fixes this but must be manually run by the DM or an admin.

Could the `/reset_channel_membership` be set to run automatically when other actions are taken? Care should be taken to only send ping after membership reset to avoid phantom pings.

e.g.
- Exclude 10 minutes after channel creation
- Trigger after `/remove_player` or `/add_player` or drop commands in the following sequence:
- Run trigger command, run reset routine, send trigger acknowledgement (ping) in channel

**Comment by OperationXen** [comment]
Coopting this issue to house the wider rework.

**Comment by OperationXen** [comment]
Channel membership is driven currently by events, a user signup, promotion from waitlist, dropout, adminstrative action such as /add_player - this is clearly not working (possibly due to a lack of error handling).

Instead (and given the change in philosophy which seems to be seeping into the project where the database is the source of truth which is represented in both discord and web ui formats) we are going to adopt a state driven approach. The database will have a model of the desired discord channel state, and a worker will attempt to manipulate reality to match that state - similarly to how ansible or react work.

**Comment by OperationXen** [comment]
This worker will run on a schedule, so there may be a slight lag in some channel membership operations but this seems acceptable for the sake of reliability.

It should also make debugging or fixing production issues easier as we can simply manipulate the database to replicate issues.
